// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foamtec.qa.security;

import com.foamtec.qa.security.AppUserIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AppUserIntegrationTest_Roo_Configurable {
    
    declare @type: AppUserIntegrationTest: @Configurable;
    
}
